# ./.github/workflows/auto-pr.yaml
name: Auto-PR
on:
  push:
    branches:
      - aestoltm-patch-1
jobs:
  pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # used implicitly by the gh CLI to authenticate with GitHub
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        gh pr create \
          --repo=${GITHUB_REPO} \
          --head=aestoltm-patch-1 \
          --base=main \
          --title="Pulling ${GITHUB_REF} into main" \
          --body=":crown: *An automated PR*"
